ci: add env aws to secret

diff --git a/.github/workflows/serverless-ci.yml b/.github/workflows/serverless-ci.yml
--- a/.github/workflows/serverless-ci.yml
+++ b/.github/workflows/serverless-ci.yml
@@ -4,7 +4,7 @@ on:
     branches:
       - release/**
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -14,18 +14,22 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.13'
-      
-      - name: Setup terraform
-        uses: opentofu/setup-opentofu@v1
+    
+        
+      - name: Restore cached virtualenv
+        uses: actions/cache/restore@v4
         with:
-          tofu_version: '1.6.0'
+          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
+          path: venv
 
       - name: Install dependencies
         run: |
           python -m venv venv
+          source venv/bin/activate
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          
+          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
+          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
 
       - name: Saved cached virtualenv
         uses: actions/cache/save@v4
@@ -41,4 +45,33 @@ jobs:
           cd lambda_package
           zip -r ../infra/lambda_function.zip .
 
-      
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Setup terraform
+        uses: opentofu/setup-opentofu@v1
+        with:
+          tofu_version: '1.6.0'
+
+      - name: Terraform Init
+        run: |
+          cd infra
+          tofu init
+
+      - name: Terraform Apply
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          set -e
+          cd infra
+          tofu apply -auto-approve || {
+            echo "Terraform apply failed. Destroying resources..."
+            tofu destroy -auto-approve
+            exit 1
+          }
